name: Firebase Deadlines Checker

on:
  schedule:
    # Esegue il controllo automatico ogni ora spaccata (Minuto 0)
    - cron: '0 * * * *'
  workflow_dispatch: # Ti permette di avviare il controllo anche a mano da GitHub per fare i test

jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        # Installa l'SDK Admin di Firebase sul server di GitHub
        run: npm install firebase-admin

      - name: Run Checker Script
        # Avvia lo script javascript che legge e scrive sul database
        run: node .github/workflows/checker.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}