name: Firebase Deadlines Checker

on:
  schedule:
    # Manteniamo il timer interno ogni 30 minuti come backup
    - cron: '*/30 * * * *'
  workflow_dispatch:
  # Questo blocco permette a servizi esterni (come cron-job.org) di svegliare il bot all'istante
  repository_dispatch:
    types: [awaken-bot]

jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install Dependencies
        run: npm install firebase-admin

      - name: Run Checker Script
        run: node .github/workflows/checker.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
