name: Firebase Deadlines Checker

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  check-db:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        # Aggiornato a v4 (supporta Node 24)
        uses: actions/checkout@v4

      - name: Setup Node.js
        # Aggiornato a v4 (supporta Node 24)
        uses: actions/setup-node@v4
        with:
          # Forza l'uso di Node 24 come richiesto da GitHub
          node-version: '24'

      - name: Install Dependencies
        run: npm install firebase-admin

      - name: Run Checker Script
        run: node .github/workflows/checker.js
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
